#!/usr/bin/env python3
"""concepts_discover.py — auto-discover concept candidates in BufferStockTheory.md.

A concept candidate is an anchor in the .md whose name doesn't follow the
known sectional / equation / theorem-numbering conventions. Specifically:

  - Bare-name anchors of the form `(X)=` where X has no `eq-`, `sec-`,
    `subsec-`, `subsubsec-`, `fig-`, `ass-`, `thm-`, `prop-`, `claim-`,
    `remark-`, `fact-`, `lemma-`, `lemm-`, `rem-`, `def-`, `clm-`, or
    `cite-` prefix. These mark places the author has explicitly named a
    concept.
  - prf-directive labels: every `:::{prf:assumption|theorem|definition|
    lemma|claim|proposition|remark|fact} ... :label: X` block. The
    label is treated as a concept-aliased anchor.

Outputs `concepts/_candidates.txt` — tab-separated rows:
  ID, line, kind, co-occurring-IDs, one-line context

Co-occurring IDs are the set of other candidate anchors that appear as
`[...](#X)` cross-references within the section starting at this
candidate's line and ending at the next candidate's line. This is the
auto-bootstrap signal for typed relations.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "BufferStockTheory.md"
OUT = ROOT / "concepts" / "_candidates.txt"

KNOWN_PREFIXES = {
    "eq", "cite", "sec", "subsec", "subsubsec",
    "fig", "ass", "thm", "prop", "claim", "remark",
    "fact", "lemma", "lemm", "rem", "def", "clm",
}

ANCHOR_RE = re.compile(r"^\(([a-zA-Z][^)]*)\)=$")
PRF_OPEN_RE = re.compile(r"^:::\{prf:([a-z]+)\}(.*)$")
LABEL_RE = re.compile(r"^:label:\s+(\S+)\s*$")
HYPERLINK_RE = re.compile(r"\[[^\]]*\]\(#([A-Za-z][A-Za-z0-9_-]*)\)")


def context_at(lines: list[str], idx0: int, lookahead: int = 6) -> str:
    """Return the first non-blank, non-anchor, non-directive line after idx0."""
    for j in range(idx0 + 1, min(idx0 + 1 + lookahead, len(lines))):
        s = lines[j].strip()
        if not s:
            continue
        if ANCHOR_RE.match(s) or s.startswith(":::") or s.startswith(":label:") or s.startswith(":name:"):
            continue
        return s[:120]
    return ""


def discover(text: str) -> list[tuple[str, int, str, str]]:
    lines = text.splitlines()
    out: list[tuple[str, int, str, str]] = []
    n = len(lines)
    i = 0
    while i < n:
        line = lines[i]
        m = ANCHOR_RE.match(line)
        if m:
            anchor = m.group(1)
            prefix = anchor.split("-", 1)[0] if "-" in anchor else anchor
            if prefix not in KNOWN_PREFIXES:
                ctx = context_at(lines, i)
                out.append((anchor, i + 1, "anchor", ctx))
            i += 1
            continue
        m = PRF_OPEN_RE.match(line)
        if m:
            kind = m.group(1)
            heading = m.group(2).strip()
            label = None
            for j in range(i + 1, min(i + 5, n)):
                lm = LABEL_RE.match(lines[j])
                if lm:
                    label = lm.group(1)
                    break
            if label:
                ctx = heading or context_at(lines, i)
                out.append((label, i + 1, f"prf-{kind}", ctx))
        i += 1
    return out


def co_occurrence(text: str, candidates: list[tuple[str, int, str, str]]) -> dict[str, set[str]]:
    lines = text.splitlines()
    n = len(lines)
    cand_ids = {c[0] for c in candidates}
    sorted_cands = sorted(candidates, key=lambda c: c[1])
    boundaries = [c[1] for c in sorted_cands] + [n + 1]
    out: dict[str, set[str]] = {c[0]: set() for c in candidates}
    for idx, (cid, start, _, _) in enumerate(sorted_cands):
        end = boundaries[idx + 1]
        chunk = "\n".join(lines[start - 1 : end - 1])
        for ref in HYPERLINK_RE.findall(chunk):
            if ref in cand_ids and ref != cid:
                out[cid].add(ref)
    return out


def main() -> int:
    if not SRC.exists():
        print(f"error: {SRC} not found", file=sys.stderr)
        return 2
    text = SRC.read_text()
    candidates = discover(text)
    co = co_occurrence(text, candidates)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write(f"# concepts/_candidates.txt — auto-generated by tools/concepts_discover.py\n")
        f.write(f"# source: {SRC.name}\n")
        f.write(f"# {len(candidates)} candidates\n")
        f.write(f"# columns: id <TAB> line <TAB> kind <TAB> cooccurs <TAB> context\n\n")
        for cid, line, kind, ctx in sorted(candidates, key=lambda c: c[1]):
            cooc = ",".join(sorted(co[cid])) or "-"
            f.write(f"{cid}\t{line}\t{kind}\t{cooc}\t{ctx}\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(candidates)} candidates)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
