#!/usr/bin/env python3
"""katex_macros_for_mpe.py — write KaTeX macro config for Markdown Preview Enhanced.

Reads `mystmd-math-macros.yml` and writes the unified MPE config at
`~/.local/state/crossnote/config.js` (MPE 0.8.x default on macOS;
override with the env var XDG_CONFIG_HOME if you've moved it). Without
this, math blocks in the rendered concept previews (and any other
paper-adjacent markdown) show "Undefined control sequence" for paper-
specific macros like \GPFacRaw, \Ex, \APFac, etc.

The output file is the same combined config MPE looks for —
`{ katexConfig: {...}, mathjaxConfig: {...}, mermaidConfig: {...} }` —
written as a parenthesised expression `({...})`, the format MPE's
config evaluator expects (it is NOT a CommonJS module.exports file).

After running:
  1. Reload the editor window: Cmd+Shift+P → "Developer: Reload Window"
  2. Open / reopen any .md file with paper math in it
  3. The paper macros now expand the same way they do in the myst HTML build.

Re-run this script whenever `mystmd-math-macros.yml` changes.

Pass an alternate output path as the only positional argument if you want
to write somewhere other than the default MPE location.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("error: PyYAML required (use /usr/bin/python3 on macOS)", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "mystmd-math-macros.yml"


def default_out() -> Path:
    """MPE 0.8.x config path. Mirrors the resolution in MPE's extension.js."""
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return Path(xdg) / "crossnote" / "config.js"
    return Path(os.path.expanduser("~/.local/state/crossnote/config.js"))


def main(argv: list[str]) -> int:
    if not SRC.exists():
        print(f"error: {SRC} not found", file=sys.stderr)
        return 2
    out = Path(argv[1]) if len(argv) > 1 else default_out()
    macros = yaml.safe_load(SRC.read_text())["project"]["math"]

    pairs = [
        f"      {json.dumps(name)}: {json.dumps(body)},"
        for name, body in sorted(macros.items())
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Auto-generated by tools/katex_macros_for_mpe.py from mystmd-math-macros.yml.\n"
        "// Re-run after macros change. Reload editor window to apply.\n"
        "\n"
        "({\n"
        "  katexConfig: {\n"
        "    // Permissive: paper macros expand to unicode chars (Ϸ for \\APFac etc.)\n"
        "    // and \\textsf/\\textrm constructs that KaTeX strict mode rejects.\n"
        "    strict: false,\n"
        "    trust: true,\n"
        "    macros: {\n"
        + "\n".join(pairs) + "\n"
        "    }\n"
        "  },\n"
        "  mathjaxConfig: {\n"
        '    "tex": {},\n'
        '    "options": {},\n'
        '    "loader": {}\n'
        "  },\n"
        "  mermaidConfig: {\n"
        '    "startOnLoad": false\n'
        "  }\n"
        "})\n"
    )
    print(f"wrote {out} ({len(macros)} macros)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
